# See http://www.appveyor.com/docs/appveyor-yml for many more options

image: Visual Studio 2017

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: NbIQ9vEo/6ZsKp4lA2FcYQYQ6BeNAkAtYbDLxQ8QJi2hIbaRVDf3DOrw5M9IMcyQ

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /^(?=.*update)(?=.*readme).*$/

build: off

# Get latest GitVersion
install:
  - choco install gitversion.portable -pre -y

# Generate version
before_test:
  - ps: \& (Join-Path $env:ChocolateyInstall 'bin\GitVersion.exe') /l console /output buildserver

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\Build.ps1