# See http://www.appveyor.com/docs/appveyor-yml for many more options

os: WMF 5

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: NbIQ9vEo/6ZsKp4lA2FcYQYQ6BeNAkAtYbDLxQ8QJi2hIbaRVDf3DOrw5M9IMcyQ

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /^(?=.*update)(?=.*readme).*$/

install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

version: '1.0.{build}'

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\Build.ps1